# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
##from ChatScreen import Ui_MainWindow

class Ui_Dialog(object):
##    def openWindow(self):
##        self.window = QtWidgets.QMainWindow()
##        self.ui = Ui_MainWindow()
##        self.ui.setupUi(self.window)
##        self.window.show()
    
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(622, 719)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 280, 521, 311))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Listen_Label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Listen_Label.setFont(font)
        self.Listen_Label.setObjectName("Listen_Label")
        self.gridLayout.addWidget(self.Listen_Label, 2, 0, 1, 1)
        self.Id_Label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Id_Label.setFont(font)
        self.Id_Label.setObjectName("Id_Label")
        self.gridLayout.addWidget(self.Id_Label, 0, 0, 1, 1)
        self.IPListen_Input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.IPListen_Input.setObjectName("IPListen_Input")
        self.gridLayout.addWidget(self.IPListen_Input, 2, 3, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PortListen_Input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.PortListen_Input.setObjectName("PortListen_Input")
        self.horizontalLayout.addWidget(self.PortListen_Input)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.PortServer_Input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.PortServer_Input.setObjectName("PortServer_Input")
        self.horizontalLayout_2.addWidget(self.PortServer_Input)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 1, 1, 1)
        self.ID_Input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.ID_Input.setObjectName("ID_Input")
        self.gridLayout.addWidget(self.ID_Input, 0, 1, 1, 1)
        self.IPServer_Input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.IPServer_Input.setObjectName("IPServer_Input")
        self.gridLayout.addWidget(self.IPServer_Input, 3, 3, 1, 1)
        self.Server_Label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Server_Label.setFont(font)
        self.Server_Label.setObjectName("Server_Label")
        self.gridLayout.addWidget(self.Server_Label, 3, 0, 1, 1)
        self.ChatApp_Label = QtWidgets.QLabel(Dialog)
        self.ChatApp_Label.setGeometry(QtCore.QRect(40, 110, 561, 151))
        font = QtGui.QFont()
        font.setPointSize(72)
        self.ChatApp_Label.setFont(font)
        self.ChatApp_Label.setObjectName("ChatApp_Label")
        self.LogInButton = QtWidgets.QPushButton(Dialog)
        self.LogInButton.setGeometry(QtCore.QRect(100, 640, 181, 61))
        self.LogInButton.setObjectName("LogInButton")
        self.ConnectionResult_Label = QtWidgets.QLabel(Dialog)
        self.ConnectionResult_Label.setGeometry(QtCore.QRect(200, 590, 201, 31))
        self.ConnectionResult_Label.setText("")
        self.ConnectionResult_Label.setObjectName("ConnectionResult_Label")
        self.StartServerButton = QtWidgets.QPushButton(Dialog)
        self.StartServerButton.setGeometry(QtCore.QRect(450, 650, 111, 41))
        self.StartServerButton.setObjectName("StartServerButton")

##        self.LogInButton.clicked.connect(self.openWindow)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.ID_Input, self.PortListen_Input)
        Dialog.setTabOrder(self.PortListen_Input, self.IPListen_Input)
        Dialog.setTabOrder(self.IPListen_Input, self.PortServer_Input)
        Dialog.setTabOrder(self.PortServer_Input, self.IPServer_Input)
        Dialog.setTabOrder(self.IPServer_Input, self.LogInButton)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Chat App"))
        self.Listen_Label.setText(_translate("Dialog", "Port/IP Listen:"))
        self.Id_Label.setText(_translate("Dialog", "ID:"))
        self.Server_Label.setText(_translate("Dialog", "Port/IP Server:"))
        self.ChatApp_Label.setText(_translate("Dialog", "CHAT APP"))
        self.LogInButton.setText(_translate("Dialog", "LogIn"))
        self.StartServerButton.setText(_translate("Dialog", "Start Server"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
